In [53]:
import pandas as pd 
df=pd.read_csv(r'C:\Users\lenovo\Desktop\Assigment\adult_with_headers (1).csv',header=0)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

In [55]:
(df.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [56]:
df.describe()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [57]:
for col in df.columns:
    print(col, (df[col] == '?').sum())

age 0
workclass 0
fnlwgt 0
education 0
education_num 0
marital_status 0
occupation 0
relationship 0
race 0
sex 0
capital_gain 0
capital_loss 0
hours_per_week 0
native_country 0
income 0

In [58]:
 import numpy as np
df.replace('?', np.nan, inplace=True)

# Check missing values again
print(df.isnull().sum())

# Drop rows with missing values (common for this dataset)
df.dropna(inplace=True)

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [59]:
 import numpy as np
num_cols = df.select_dtypes(include=['int64']).columns
num_cols

Index(['age', 'fnlwgt', 'education_num', 'capital_gain', 'capital_loss',
       'hours_per_week'],
      dtype='object')

In [60]:
cat_cols=df.select_dtypes(include=['object']).columns
print(cat_cols)

Index(['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income'],
      dtype='object')

In [61]:
df1=df[['age','fnlwgt','education_num','capital_gain','capital_loss','hours_per_week']]
df1

       age  fnlwgt  education_num  capital_gain  capital_loss  hours_per_week
0       39   77516             13          2174             0              40
1       50   83311             13             0             0              13
2       38  215646              9             0             0              40
3       53  234721              7             0             0              40
4       28  338409             13             0             0              40
...    ...     ...            ...           ...           ...             ...
32556   27  257302             12             0             0              38
32557   40  154374              9             0             0              40
32558   58  151910              9             0             0              40
32559   22  201490              9             0             0              20
32560   52  287927              9         15024             0              40

[32561 rows x 6 columns]

In [62]:
from sklearn.preprocessing import StandardScaler
Scaler=StandardScaler()
x_trs=Scaler.fit_transform(df1)
x_trs=pd.DataFrame(x_trs,columns=df1.columns)
x_trs

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.030671,-1.063611,1.134739,0.148453,-0.21666,-0.035429
1,0.837109,-1.008707,1.134739,-0.145920,-0.21666,-2.222153
2,-0.042642,0.245079,-0.420060,-0.145920,-0.21666,-0.035429
3,1.057047,0.425801,-1.197459,-0.145920,-0.21666,-0.035429
4,-0.775768,1.408176,1.134739,-0.145920,-0.21666,-0.035429
...,...,...,...,...,...,...
32556,-0.849080,0.639741,0.746039,-0.145920,-0.21666,-0.197409
32557,0.103983,-0.335433,-0.420060,-0.145920,-0.21666,-0.035429
32558,1.423610,-0.358777,-0.420060,-0.145920,-0.21666,-0.035429
32559,-1.215643,0.110960,-0.420060,-0.145920,-0.21666,-1.655225
32560,0.983734,0.929893,-0.420060,1.888424,-0.21666,-0.035429

In [63]:
from sklearn.preprocessing import  MinMaxScaler
Scaler= MinMaxScaler()
x_trsm=Scaler.fit_transform(df1)
x_trsm=pd.DataFrame(x_trsm,columns=df1.columns)
x_trsm

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.301370,0.044302,0.800000,0.021740,0.0,0.397959
1,0.452055,0.048238,0.800000,0.000000,0.0,0.122449
2,0.287671,0.138113,0.533333,0.000000,0.0,0.397959
3,0.493151,0.151068,0.400000,0.000000,0.0,0.397959
4,0.150685,0.221488,0.800000,0.000000,0.0,0.397959
...,...,...,...,...,...,...
32556,0.136986,0.166404,0.733333,0.000000,0.0,0.377551
32557,0.315068,0.096500,0.533333,0.000000,0.0,0.397959
32558,0.561644,0.094827,0.533333,0.000000,0.0,0.397959
32559,0.068493,0.128499,0.533333,0.000000,0.0,0.193878
32560,0.479452,0.187203,0.533333,0.150242,0.0,0.397959

In [64]:
df2=df[['workclass', 'education', 'marital_status', 'occupation',
       'relationship', 'race', 'sex', 'native_country', 'income']]
df2

,workclass,education,marital_status,occupation,relationship,race,sex,native_country,income
0,State-gov,Bachelors,Never-married,Adm-clerical,Not-in-family,White,Male,United-States,<=50K
1,Self-emp-not-inc,Bachelors,Married-civ-spouse,Exec-managerial,Husband,White,Male,United-States,<=50K
2,Private,HS-grad,Divorced,Handlers-cleaners,Not-in-family,White,Male,United-States,<=50K
3,Private,11th,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,United-States,<=50K
4,Private,Bachelors,Married-civ-spouse,Prof-specialty,Wife,Black,Female,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...
32556,Private,Assoc-acdm,Married-civ-spouse,Tech-support,Wife,White,Female,United-States,<=50K
32557,Private,HS-grad,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,United-States,>50K
32558,Private,HS-grad,Widowed,Adm-clerical,Unmarried,White,Female,United-States,<=50K
32559,Private,HS-grad,Never-married,Adm-clerical,Own-child,White,Male,United-States,<=50K
32560,Self-emp-inc,HS-grad,Married-civ-spouse,Exec-managerial,Wife,White,Female,United-States,>50K

In [65]:
# Create LabelEncoder object
le = LabelEncoder()

# Find categorical columns
cat_cols = df.select_dtypes(include='object').columns

# Apply Label Encoding
for col in cat_cols:
    df[col] = le.fit_transform(df[col])
    print(df)

       age  workclass  fnlwgt    education  education_num  \
0       39          7   77516    Bachelors             13
1       50          6   83311    Bachelors             13
2       38          4  215646      HS-grad              9
3       53          4  234721         11th              7
4       28          4  338409    Bachelors             13
...    ...        ...     ...          ...            ...
32556   27          4  257302   Assoc-acdm             12
32557   40          4  154374      HS-grad              9
32558   58          4  151910      HS-grad              9
32559   22          4  201490      HS-grad              9
32560   52          5  287927      HS-grad              9

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White
1       Married-civ-spouse     Exec-managerial         Husband   White
2                 Divorced   Handlers-cleaners   Not-in-family   White
3       Married-civ-spouse   Handlers-cleaners         Husband   Black
4       Married-civ-spouse      Prof-specialty            Wife   Black
...                    ...                 ...             ...     ...
32556   Married-civ-spouse        Tech-support            Wife   White
32557   Married-civ-spouse   Machine-op-inspct         Husband   White
32558              Widowed        Adm-clerical       Unmarried   White
32559        Never-married        Adm-clerical       Own-child   White
32560   Married-civ-spouse     Exec-managerial            Wife   White

           sex  capital_gain  capital_loss  hours_per_week  native_country  \
0         Male          2174             0              40   United-States
1         Male             0             0              13   United-States
2         Male             0             0              40   United-States
3         Male             0             0              40   United-States
4       Female             0             0              40            Cuba
...        ...           ...           ...             ...             ...
32556   Female             0             0              38   United-States
32557     Male             0             0              40   United-States
32558   Female             0             0              40   United-States
32559     Male             0             0              20   United-States
32560   Female         15024             0              40   United-States

       income
0       <=50K
1       <=50K
2       <=50K
3       <=50K
4       <=50K
...       ...
32556   <=50K
32557    >50K
32558   <=50K
32559   <=50K
32560    >50K

[32561 rows x 15 columns]
       age  workclass  fnlwgt  education  education_num       marital_status  \
0       39          7   77516          9             13        Never-married
1       50          6   83311          9             13   Married-civ-spouse
2       38          4  215646         11              9             Divorced
3       53          4  234721          1              7   Married-civ-spouse
4       28          4  338409          9             13   Married-civ-spouse
...    ...        ...     ...        ...            ...                  ...
32556   27          4  257302          7             12   Married-civ-spouse
32557   40          4  154374         11              9   Married-civ-spouse
32558   58          4  151910         11              9              Widowed
32559   22          4  201490         11              9        Never-married
32560   52          5  287927         11              9   Married-civ-spouse

               occupation    relationship    race      sex  capital_gain  \
0            Adm-clerical   Not-in-family   White     Male          2174
1         Exec-managerial         Husband   White     Male             0
2       Handlers-cleaners   Not-in-family   White     Male             0
3       Handlers-cleaners         Husband   Black     Male             0
4          Prof-specialty            Wife   Black   Female             0
...                   ...             ...     ...      ...           ...
32556        Tech-support            Wife   White   Female             0
32557   Machine-op-inspct         Husband   White     Male             0
32558        Adm-clerical       Unmarried   White   Female             0
32559        Adm-clerical       Own-child   White     Male             0
32560     Exec-managerial            Wife   White   Female         15024

       capital_loss  hours_per_week  native_country  income
0                 0              40   United-States   <=50K
1                 0              13   United-States   <=50K
2                 0              40   United-States   <=50K
3                 0              40   United-States   <=50K
4                 0              40            Cuba   <=50K
...             ...             ...             ...     ...
32556             0              38   United-States   <=50K
32557             0              40   United-States    >50K
32558             0              40   United-States   <=50K
32559             0              20   United-States   <=50K
32560             0              40   United-States    >50K

[32561 rows x 15 columns]
       age  workclass  fnlwgt  education  education_num  marital_status  \
0       39          7   77516          9             13               4
1       50          6   83311          9             13               2
2       38          4  215646         11              9               0
3       53          4  234721          1              7               2
4       28          4  338409          9             13               2
...    ...        ...     ...        ...            ...             ...
32556   27          4  257302          7             12               2
32557   40          4  154374         11              9               2
32558   58          4  151910         11              9               6
32559   22          4  201490         11              9               4
32560   52          5  287927         11              9               2

               occupation    relationship    race      sex  capital_gain  \
0            Adm-clerical   Not-in-family   White     Male          2174
1         Exec-managerial         Husband   White     Male             0
2       Handlers-cleaners   Not-in-family   White     Male             0
3       Handlers-cleaners         Husband   Black     Male             0
4          Prof-specialty            Wife   Black   Female             0
...                   ...             ...     ...      ...           ...
32556        Tech-support            Wife   White   Female             0
32557   Machine-op-inspct         Husband   White     Male             0
32558        Adm-clerical       Unmarried   White   Female             0
32559        Adm-clerical       Own-child   White     Male             0
32560     Exec-managerial            Wife   White   Female         15024

       capital_loss  hours_per_week  native_country  income
0                 0              40   United-States   <=50K
1                 0              13   United-States   <=50K
2                 0              40   United-States   <=50K
3                 0              40   United-States   <=50K
4                 0              40            Cuba   <=50K
...             ...             ...             ...     ...
32556             0              38   United-States   <=50K
32557             0              40   United-States    >50K
32558             0              40   United-States   <=50K
32559             0              20   United-States   <=50K
32560             0              40   United-States    >50K

[32561 rows x 15 columns]
       age  workclass  fnlwgt  education  education_num  marital_status  \
0       39          7   77516          9             13               4
1       50          6   83311          9             13               2
2       38          4  215646         11              9               0
3       53          4  234721          1              7               2
4       28          4  338409          9             13               2
...    ...        ...     ...        ...            ...             ...
32556   27          4  257302          7             12               2
32557   40          4  154374         11              9               2
32558   58          4  151910         11              9               6
32559   22          4  201490         11              9               4
32560   52          5  287927         11              9               2

       occupation    relationship    race      sex  capital_gain  \
0               1   Not-in-family   White     Male          2174
1               4         Husband   White     Male             0
2               6   Not-in-family   White     Male             0
3               6         Husband   Black     Male             0
4              10            Wife   Black   Female             0
...           ...             ...     ...      ...           ...
32556          13            Wife   White   Female             0
32557           7         Husband   White     Male             0
32558           1       Unmarried   White   Female             0
32559           1       Own-child   White     Male             0
32560           4            Wife   White   Female         15024

       capital_loss  hours_per_week  native_country  income
0                 0              40   United-States   <=50K
1                 0              13   United-States   <=50K
2                 0              40   United-States   <=50K
3                 0              40   United-States   <=50K
4                 0              40            Cuba   <=50K
...             ...             ...             ...     ...
32556             0              38   United-States   <=50K
32557             0              40   United-States    >50K
32558             0              40   United-States   <=50K
32559             0              20   United-States   <=50K
32560             0              40   United-States    >50K

[32561 rows x 15 columns]
       age  workclass  fnlwgt  education  education_num  marital_status  \
0       39          7   77516          9             13               4
1       50          6   83311          9             13               2
2       38          4  215646         11              9               0
3       53          4  234721          1              7               2
4       28          4  338409          9             13               2
...    ...        ...     ...        ...            ...             ...
32556   27          4  257302          7             12               2
32557   40          4  154374         11              9               2
32558   58          4  151910         11              9               6
32559   22          4  201490         11              9               4
32560   52          5  287927         11              9               2

       occupation  relationship    race      sex  capital_gain  capital_loss  \
0               1             1   White     Male          2174             0
1               4             0   White     Male             0             0
2               6             1   White     Male             0             0
3               6             0   Black     Male             0             0
4              10             5   Black   Female             0             0
...           ...           ...     ...      ...           ...           ...
32556          13             5   White   Female             0             0
32557           7             0   White     Male             0             0
32558           1             4   White   Female             0             0
32559           1             3   White     Male             0             0
32560           4             5   White   Female         15024             0

       hours_per_week  native_country  income
0                  40   United-States   <=50K
1                  13   United-States   <=50K
2                  40   United-States   <=50K
3                  40   United-States   <=50K
4                  40            Cuba   <=50K
...               ...             ...     ...
32556              38   United-States   <=50K
32557              40   United-States    >50K
32558              40   United-States   <=50K
32559              20   United-States   <=50K
32560              40   United-States    >50K

[32561 rows x 15 columns]
       age  workclass  fnlwgt  education  education_num  marital_status  \
0       39          7   77516          9             13               4
1       50          6   83311          9             13               2
2       38          4  215646         11              9               0
3       53          4  234721          1              7               2
4       28          4  338409          9             13               2
...    ...        ...     ...        ...            ...             ...
32556   27          4  257302          7             12               2
32557   40          4  154374         11              9               2
32558   58          4  151910         11              9               6
32559   22          4  201490         11              9               4
32560   52          5  287927         11              9               2

       occupation  relationship  race      sex  capital_gain  capital_loss  \
0               1             1     4     Male          2174             0
1               4             0     4     Male             0             0
2               6             1     4     Male             0             0
3               6             0     2     Male             0             0
4              10             5     2   Female             0             0
...           ...           ...   ...      ...           ...           ...
32556          13             5     4   Female             0             0
32557           7             0     4     Male             0             0
32558           1             4     4   Female             0             0
32559           1             3     4     Male             0             0
32560           4             5     4   Female         15024             0

       hours_per_week  native_country  income
0                  40   United-States   <=50K
1                  13   United-States   <=50K
2                  40   United-States   <=50K
3                  40   United-States   <=50K
4                  40            Cuba   <=50K
...               ...             ...     ...
32556              38   United-States   <=50K
32557              40   United-States    >50K
32558              40   United-States   <=50K
32559              20   United-States   <=50K
32560              40   United-States    >50K

[32561 rows x 15 columns]
       age  workclass  fnlwgt  education  education_num  marital_status  \
0       39          7   77516          9             13               4
1       50          6   83311          9             13               2
2       38          4  215646         11              9               0
3       53          4  234721          1              7               2
4       28          4  338409          9             13               2
...    ...        ...     ...        ...            ...             ...
32556   27          4  257302          7             12               2
32557   40          4  154374         11              9               2
32558   58          4  151910         11              9               6
32559   22          4  201490         11              9               4
32560   52          5  287927         11              9               2

       occupation  relationship  race  sex  capital_gain  capital_loss  \
0               1             1     4    1          2174             0
1               4             0     4    1             0             0
2               6             1     4    1             0             0
3               6             0     2    1             0             0
4              10             5     2    0             0             0
...           ...           ...   ...  ...           ...           ...
32556          13             5     4    0             0             0
32557           7             0     4    1             0             0
32558           1             4     4    0             0             0
32559           1             3     4    1             0             0
32560           4             5     4    0         15024             0

       hours_per_week  native_country  income
0                  40   United-States   <=50K
1                  13   United-States   <=50K
2                  40   United-States   <=50K
3                  40   United-States   <=50K
4                  40            Cuba   <=50K
...               ...             ...     ...
32556              38   United-States   <=50K
32557              40   United-States    >50K
32558              40   United-States   <=50K
32559              20   United-States   <=50K
32560              40   United-States    >50K

[32561 rows x 15 columns]
       age  workclass  fnlwgt  education  education_num  marital_status  \
0       39          7   77516          9             13               4
1       50          6   83311          9             13               2
2       38          4  215646         11              9               0
3       53          4  234721          1              7               2
4       28          4  338409          9             13               2
...    ...        ...     ...        ...            ...             ...
32556   27          4  257302          7             12               2
32557   40          4  154374         11              9               2
32558   58          4  151910         11              9               6
32559   22          4  201490         11              9               4
32560   52          5  287927         11              9               2

       occupation  relationship  race  sex  capital_gain  capital_loss  \
0               1             1     4    1          2174             0
1               4             0     4    1             0             0
2               6             1     4    1             0             0
3               6             0     2    1             0             0
4              10             5     2    0             0             0
...           ...           ...   ...  ...           ...           ...
32556          13             5     4    0             0             0
32557           7             0     4    1             0             0
32558           1             4     4    0             0             0
32559           1             3     4    1             0             0
32560           4             5     4    0         15024             0

       hours_per_week  native_country  income
0                  40              39   <=50K
1                  13              39   <=50K
2                  40              39   <=50K
3                  40              39   <=50K
4                  40               5   <=50K
...               ...             ...     ...
32556              38              39   <=50K
32557              40              39    >50K
32558              40              39   <=50K
32559              20              39   <=50K
32560              40              39    >50K

[32561 rows x 15 columns]
       age  workclass  fnlwgt  education  education_num  marital_status  \
0       39          7   77516          9             13               4
1       50          6   83311          9             13               2
2       38          4  215646         11              9               0
3       53          4  234721          1              7               2
4       28          4  338409          9             13               2
...    ...        ...     ...        ...            ...             ...

In [66]:
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,7,77516,9,13,4,1,1,4,1,2174,0,40,39,0
1,50,6,83311,9,13,2,4,0,4,1,0,0,13,39,0
2,38,4,215646,11,9,0,6,1,4,1,0,0,40,39,0
3,53,4,234721,1,7,2,6,0,2,1,0,0,40,39,0
4,28,4,338409,9,13,2,10,5,2,0,0,0,40,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,4,257302,7,12,2,13,5,4,0,0,0,38,39,0
32557,40,4,154374,11,9,2,7,0,4,1,0,0,40,39,1
32558,58,4,151910,11,9,6,1,4,4,0,0,0,40,39,0
32559,22,4,201490,11,9,4,1,3,4,1,0,0,20,39,0
32560,52,5,287927,11,9,2,4,5,4,0,15024,0,40,39,1

In [67]:
df3=df=pd.read_csv(r'C:\Users\lenovo\Desktop\Assigment\adult_with_headers (1).csv',header=0)
df3

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [68]:
import pandas as pd

# Find categorical columns
cat_cols = df3.select_dtypes(include='object').columns

# Apply One-Hot Encoding
df_encoded = pd.get_dummies(df3, columns=cat_cols)

print(df_encoded.head())

   age  fnlwgt  education_num  capital_gain  capital_loss  hours_per_week  \
0   39   77516             13          2174             0              40
1   50   83311             13             0             0              13
2   38  215646              9             0             0              40
3   53  234721              7             0             0              40
4   28  338409             13             0             0              40

   workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  \
0         False                   False                 False
1         False                   False                 False
2         False                   False                 False
3         False                   False                 False
4         False                   False                 False

   workclass_ Never-worked  ...  native_country_ Scotland  \
0                    False  ...                     False
1                    False  ...                     False
2                    False  ...                     False
3                    False  ...                     False
4                    False  ...                     False

   native_country_ South  native_country_ Taiwan  native_country_ Thailand  \
0                  False                   False                     False
1                  False                   False                     False
2                  False                   False                     False
3                  False                   False                     False
4                  False                   False                     False

   native_country_ Trinadad&Tobago  native_country_ United-States  \
0                            False                           True
1                            False                           True
2                            False                           True
3                            False                           True
4                            False                          False

   native_country_ Vietnam  native_country_ Yugoslavia  income_ <=50K  \
0                    False                       False           True
1                    False                       False           True
2                    False                       False           True
3                    False                       False           True
4                    False                       False           True

   income_ >50K
0         False
1         False
2         False
3         False
4         False

[5 rows x 110 columns]

In [69]:
import pandas as pd

# Find categorical columns
cat_cols = df3.select_dtypes(include='object').columns

# Apply One-Hot Encoding
df_encoded = pd.get_dummies(df3, columns=cat_cols)

print(df_encoded.head())

   age  fnlwgt  education_num  capital_gain  capital_loss  hours_per_week  \
0   39   77516             13          2174             0              40
1   50   83311             13             0             0              13
2   38  215646              9             0             0              40
3   53  234721              7             0             0              40
4   28  338409             13             0             0              40

   workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  \
0         False                   False                 False
1         False                   False                 False
2         False                   False                 False
3         False                   False                 False
4         False                   False                 False

   workclass_ Never-worked  ...  native_country_ Scotland  \
0                    False  ...                     False
1                    False  ...                     False
2                    False  ...                     False
3                    False  ...                     False
4                    False  ...                     False

   native_country_ South  native_country_ Taiwan  native_country_ Thailand  \
0                  False                   False                     False
1                  False                   False                     False
2                  False                   False                     False
3                  False                   False                     False
4                  False                   False                     False

   native_country_ Trinadad&Tobago  native_country_ United-States  \
0                            False                           True
1                            False                           True
2                            False                           True
3                            False                           True
4                            False                          False

   native_country_ Vietnam  native_country_ Yugoslavia  income_ <=50K  \
0                    False                       False           True
1                    False                       False           True
2                    False                       False           True
3                    False                       False           True
4                    False                       False           True

   income_ >50K
0         False
1         False
2         False
3         False
4         False

[5 rows x 110 columns]

In [70]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder(sparse_output=False)

encoded = ohe.fit_transform(df3[cat_cols])

encoded_df = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out(cat_cols)
)

df_encoded = pd.concat(
    [df3.drop(columns=cat_cols), encoded_df],
    axis=1
)

print(df_encoded.head())

   age  fnlwgt  education_num  capital_gain  capital_loss  hours_per_week  \
0   39   77516             13          2174             0              40
1   50   83311             13             0             0              13
2   38  215646              9             0             0              40
3   53  234721              7             0             0              40
4   28  338409             13             0             0              40

   workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  \
0           0.0                     0.0                   0.0
1           0.0                     0.0                   0.0
2           0.0                     0.0                   0.0
3           0.0                     0.0                   0.0
4           0.0                     0.0                   0.0

   workclass_ Never-worked  ...  native_country_ Scotland  \
0                      0.0  ...                       0.0
1                      0.0  ...                       0.0
2                      0.0  ...                       0.0
3                      0.0  ...                       0.0
4                      0.0  ...                       0.0

   native_country_ South  native_country_ Taiwan  native_country_ Thailand  \
0                    0.0                     0.0                       0.0
1                    0.0                     0.0                       0.0
2                    0.0                     0.0                       0.0
3                    0.0                     0.0                       0.0
4                    0.0                     0.0                       0.0

   native_country_ Trinadad&Tobago  native_country_ United-States  \
0                              0.0                            1.0
1                              0.0                            1.0
2                              0.0                            1.0
3                              0.0                            1.0
4                              0.0                            0.0

   native_country_ Vietnam  native_country_ Yugoslavia  income_ <=50K  \
0                      0.0                         0.0            1.0
1                      0.0                         0.0            1.0
2                      0.0                         0.0            1.0
3                      0.0                         0.0            1.0
4                      0.0                         0.0            1.0

   income_ >50K
0           0.0
1           0.0
2           0.0
3           0.0
4           0.0

[5 rows x 110 columns]