In [1]:
import pandas as pd
df=pd.read_csv(r'C:\Users\lenovo\Desktop\Assigmrnt\Patient_Data (1).csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [2]:
df2=df[['PatientID','Department','Doctor','BillAmount']]
df2

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [3]:
df3=df.drop(columns=['ReceptionistID','CheckInTime'])

In [4]:
df3

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [5]:
df3.groupby('Department')['BillAmount'].sum()

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [6]:
df3.drop_duplicates(subset='PatientID',inplace=True)
df3

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [7]:
df3['BillAmount']=df3['BillAmount'].fillna(df3['BillAmount'].mean())

In [8]:
df3

   PatientID     Name   Department     Doctor   BillAmount
0        101    Alice   Cardiology  Dr. Smith  5000.000000
1        102      Bob    Neurology   Dr. John  6233.333333
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000
3        104    David   Cardiology  Dr. Smith  6200.000000
4        105      Eva  Dermatology   Dr. Rose  6233.333333

In [9]:
df4=pd.read_csv(r'C:\Users\lenovo\Desktop\Assigmrnt\Billing_Data (1).csv')
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [10]:
df5=pd.merge(df3,df4,on='PatientID')

In [11]:
df5

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [12]:
df_new_patient=pd.DataFrame({'PatientID':['106','108','102'], 'Name':['alex','bobby','Bob'],'Department':['Cardiology','Cardiology','Neurology'],'Doctor':['Dr. Smith','Dr. Smith',
                             'Dr. John'],'BillAmount':[5000,2000,6233.33],'InsuranceCovered':['2000','2000','1500'],'FinalAmount':[3000,2000,3500]})

In [13]:
df_new_patient

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,106,alex,Cardiology,Dr. Smith,5000.00,2000,3000
1,108,bobby,Cardiology,Dr. Smith,2000.00,2000,2000
2,102,Bob,Neurology,Dr. John,6233.33,1500,3500

In [14]:
final_df_rowwise=pd.concat([df5,df_new_patient],axis=0)

In [15]:
final_df_rowwise

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000
0,106,alex,Cardiology,Dr. Smith,5000.000000,2000,3000
1,108,bobby,Cardiology,Dr. Smith,2000.000000,2000,2000
2,102,Bob,Neurology,Dr. John,6233.330000,1500,3500

In [16]:
final_df_columnwise=pd.concat([df5,df_new_patient],axis=1,)

In [17]:
final_df_columnwise

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000,106,alex,Cardiology,Dr. Smith,5000.00,2000,3000.0
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500,108,bobby,Cardiology,Dr. Smith,2000.00,2000,2000.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000,102,Bob,Neurology,Dr. John,6233.33,1500,3500.0
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000,NaN,NaN,NaN,NaN,NaN,NaN,NaN